database: "GISAID"
reference: "config/reference.fasta"
genome_annotation: "config/genome_annotation.gff3"
genbank_reference: "config/reference.gb"
include: "config/Lineage-B/include_GISAID.txt"
exclude: "config/exclude_accessions.txt"
clades: "config/clades.tsv"
lat_longs: "config/lat_longs.tsv"
auspice_config: "config/Lineage-B/auspice_GISAID.json"
description: "config/description.md"
tree_mask: "config/tree_mask.tsv"
color_order: "config/color_ordering.tsv"
color_scheme: "config/color_schemes.tsv"

# Use `accession` as the ID column since `strain` currently contains duplicates¹.
# ¹ https://github.com/nextstrain/mpox/issues/33
strain_id_field: "accession"
display_strain_field: "strain"

build_name: "Lineage-B-GISAID"
auspice_name: "Lineage-B-GISAID"

filter:
  min_date: 2022
  min_length: 160000
  exclude_where: "database!=GISAID"

subsample:
  Lineage_B:
    group_by: ""
    sequences_per_group: ""
    other_filters: "clade!=IIb"
    exclude_lineages:
      - B.1
      - A
      - A.1
      - A.1.1
      - A.2
      - A.2.1
      - A.2.2
      - A.2.3
      - A.3
  B1_in_2022:
    group_by: "--group-by month country"
    sequences_per_group: "--subsample-max-sequences 1000"
    other_filters: "--exclude-where lineage!=B.1 date_year=2022"
  B1_after_2022:
    group_by: ""
    sequences_per_group: ""
    other_filters: "--exclude-where lineage!=B.1 date_year!=2022"

## align
max_indel: 10000
seed_spacing: 1000

## treefix
fix_tree: false
treefix_root: "--root EPI_ISL_15912087"

## refine
timetree: true
root: "EPI_ISL_15912087"
clock_rate: 5.7e-5
clock_std_dev: 2e-5
divergence_units: "mutations"

traits:
  columns: ["region", "country", "division"]
  sampling_bias_correction: 3

## recency
recency: false

mask:
  from_beginning: 800
  from_end: 6422
  maskfile: "config/mask.bed"

frequency:
  min_date: "2022-01-01"
