database: "GenBank"
reference: "config/reference.fasta"
genome_annotation: "config/genome_annotation.gff3"
genbank_reference: "config/reference.gb"
include: "config/All-Clades/include.txt"
exclude: "config/exclude_accessions.txt"
clades: "config/clades.tsv"
lat_longs: "config/lat_longs.tsv"
auspice_config: "config/All-Clades/auspice.json"
description: "config/description.md"
tree_mask: "config/tree_mask.tsv"
color_order: "config/color_ordering.tsv"
color_scheme: "config/color_schemes.tsv"

# Use `accession` as the ID column since `strain` currently contains duplicates¹.
# ¹ https://github.com/nextstrain/mpox/issues/33
strain_id_field: "accession"
display_strain_field: "strain"

build_name: "All-Clades"
auspice_name: "All-Clades"

filter:
  min_date: 1950
  min_length: 160000
  exclude_where: "database!=GenBank"

### Set 1: Non-B.1 sequences: use all
### Set 2: B.1 sequences: small sample across year/country/lineage
subsample:
  non_B1:
    group_by: ""
    sequences_per_group: ""
    exclude_lineages:
      - B.1
      - B.1.1
      - B.1.2
      - B.1.3
      - B.1.4
      - B.1.5
      - B.1.6
      - B.1.7
      - B.1.8
      - B.1.9
      - B.1.10
      - B.1.11
      - B.1.12
      - B.1.13
      - B.1.14
      - B.1.15
      - B.1.16
      - B.1.17
      - B.1.18
      - B.1.19
      - B.1.20
      - B.1.21
      - B.1.22
      - C.1
      - C.1.1
  B1:
    group_by: "--group-by lineage country year"
    sequences_per_group: "--sequences-per-group 5"
    other_filters: "clade!=IIb"
    exclude_lineages:
      - A
      - A.1
      - A.1.1
      - A.2
      - A.2.1
      - A.2.2
      - A.2.3
      - A.3

## align
max_indel: 10000
seed_spacing: 1000

## treefix
fix_tree: true

## refine
timetree: false
root: "best"
clock_rate: 3e-6
clock_std_dev: 6e-6
divergence_units: "mutations-per-site"

traits:
  columns: ""
  sampling_bias_correction: 3

## recency
recency: false

mask:
  from_beginning: 1350
  from_end: 6422
  maskfile: "config/mask_overview.bed"

frequency:
  min_date: "1970-01-01"
