database: "GISAID"
reference: "config/reference.fasta"
genome_annotation: "config/genome_annotation.gff3"
genbank_reference: "config/reference.gb"
include: "config/Clade-IIb/include.txt"
exclude: "config/exclude_accessions.txt"
clades: "config/clades.tsv"
lat_longs: "config/lat_longs.tsv"
auspice_config: "config/Clade-IIb/auspice_GISAID.json"
description: "config/description.md"
tree_mask: "config/tree_mask.tsv"
color_order: "config/color_ordering.tsv"
color_scheme: "config/color_schemes.tsv"

# Use `accession` as the ID column since `strain` currently contains duplicates¹.
# ¹ https://github.com/nextstrain/mpox/issues/33
strain_id_field: "accession"
display_strain_field: "strain"

build_name: "Clade-IIb-GISAID"
auspice_name: "Clade-IIb-GISAID"

filter:
  min_date: 2017
  min_length: 160000
  exclude_where: "database!=GISAID"

subsample:
  IIb:
    group_by: ""
    sequences_per_group: ""
    other_filters: "--exclude-where clade!=IIb"

## align
max_indel: 10000
seed_spacing: 1000

## treefix
fix_tree: false
treefix_root: "--root EPI_ISL_13056280"

## refine
timetree: true
root: "EPI_ISL_13056280 EPI_ISL_13056278"
clock_rate: 5.7e-5
clock_std_dev: 2e-5
divergence_units: "mutations"

traits:
  columns: ["region", "country", "division"]
  sampling_bias_correction: 3

## recency
recency: false

mask:
  from_beginning: 800
  from_end: 6422
  maskfile: "config/mask.bed"

frequency:
  min_date: "2017-01-01"
