database: "GenBank"
reference: "config/reference.fasta"
genome_annotation: "config/genome_annotation.gff3"
genbank_reference: "config/reference.gb"
include: "config/Clade-IIb/include_GenBank.txt"
exclude: "config/exclude_accessions.txt"
clades: "config/clades.tsv"
lat_longs: "config/lat_longs.tsv"
auspice_config: "config/Clade-IIb/auspice_GenBank.json"
description: "config/description.md"
tree_mask: "config/tree_mask.tsv"
color_order: "config/color_ordering.tsv"
color_scheme: "config/color_schemes.tsv"

# Use `accession` as the ID column since `strain` currently contains duplicates¹.
# ¹ https://github.com/nextstrain/mpox/issues/33
strain_id_field: "accession"
display_strain_field: "strain"

build_name: "Clade-IIb-GenBank"
auspice_name: "Clade-IIb-GenBank"

filter:
  min_date: 2017
  min_length: 160000
  exclude_where: "database!=GenBank"

subsample:
  IIb_in_2022:
    group_by: "--group-by month lineage"
    sequences_per_group: "--sequences-per-group 20"
    other_filters: "--exclude-where clade!=IIb date_year!=2022"
  IIb_Others:
    group_by: ""
    sequences_per_group: ""
    other_filters: "--exclude-where clade!=IIb date_year=2022"
  Recent2weeks:
    group_by: ""
    sequences_per_group: ""
    other_filters: "--exclude-where clade!=IIb update!='1-2 weeks ago'"
  Recent1week:
    group_by: ""
    sequences_per_group: ""
    other_filters: "--exclude-where clade!=IIb update!='< 1 week'"

## align
max_indel: 10000
seed_spacing: 1000

## treefix
fix_tree: false
treefix_root: "--root MK783032"

## refine
timetree: true
root: "MK783032 MK783030"
clock_rate: 5.7e-5
clock_std_dev: 2e-5
divergence_units: "mutations"

traits:
  columns: ["region", "country", "division"]
  sampling_bias_correction: 3

## recency
recency: false

mask:
  from_beginning: 800
  from_end: 6422
  maskfile: "config/mask.bed"

frequency:
  min_date: "2017-01-01"
