database: "GenBank"
reference: "config/reference.fasta"
genome_annotation: "config/genome_annotation.gff3"
genbank_reference: "config/reference.gb"
include: "config/Clade-I/include.txt"
exclude: "config/exclude_accessions.txt"
clades: "config/clades.tsv"
lat_longs: "config/lat_longs.tsv"
auspice_config: "config/Clade-I/auspice_GenBank.json"
description: "config/description.md"
tree_mask: "config/tree_mask.tsv"
color_order: "config/color_ordering.tsv"
color_scheme: "config/color_schemes.tsv"

# Use `accession` as the ID column since `strain` currently contains duplicates¹.
# ¹ https://github.com/nextstrain/mpox/issues/33
strain_id_field: "accession"
display_strain_field: "strain"

build_name: "Clade-I-GenBank"
auspice_name: "Clade-I-GenBank"

filter:
  min_date: 1900
  min_length: 100000
  exclude_where: "database!=GenBank"

subsample:
  Ia:
    group_by: ""
    sequences_per_group: ""
    other_filters: "--exclude-where clade!=Ia"
  Ib:
    group_by: ""
    sequences_per_group: ""
    other_filters: "--exclude-where clade!=Ib"

## align
max_indel: 10000
seed_spacing: 1000

## treefix
fix_tree: true
treefix_root: "" # without a root we'll midpoint root which should work great for clade I

## refine
timetree: true
root: "best"
# Clock rate chosen via treetime inference on Clade-I data excluding Clade-Ib seqs (n=73)
# TODO: update this once more public data is available.
clock_rate: 1.465e-06
clock_std_dev: 6.7e-07
divergence_units: "mutations"

traits:
  columns: ["region", "country", "division"]
  sampling_bias_correction: 3

## recency
recency: false

mask:
  from_beginning: 800
  from_end: 6422
  maskfile: "config/mask.bed"

frequency:
  min_date: "2023-01-01"
